name: "[BACKEND] Deploy Cloud Run"

on:
  push:
    branches: [main]
    paths:
      - backend/**

  workflow_dispatch:

defaults:
  run:
    working-directory: backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GCP Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to GCP Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: kg1-backend
          source: .
          region: europe-west1
