name: "[BACKEND] Run DB Migration"

on:
  push:
    branches: [main]
    paths:
      - backend/prisma/migrations/**

  workflow_dispatch:

defaults:
  run:
    working-directory: backend

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_DIRECT_URL: ${{ secrets.DATABASE_DIRECT_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run DB Migration
        run: |
          npm ci
          npx prisma migrate deploy
